### ISSUE TITLE
编写绿盟扫描器下载工具

### ISSUE THREAD

**Issue by jscdy** [s0nd9r/RSAS_Task_Tool#1]
大佬，我这边想写一个绿盟扫描器下载的工具，功能是基于下载的报告，读取报告中所有的ip以及ip所对应的开放端口。最终以excel形式保存。这边你有空可以一起交流一下吗？我记得之前有人写过这个工具的，但是找不到了。麻烦回复我一下哦。我的QQ：2415634794

**Comment by fengshao312** [comment]
https://github.com/fengshao312/RSAS-Data-Export 是这个工具吧
